services:
  db:
    container_name: OAuthJWT_db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3305:3306"
    volumes:
      - mysql_jwt_db:/var/lib/mysql

volumes:
  mysql_jwt_db:

