spring.application.name=SecurityJWT

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jwt.secret=${SPRING_JWT_SECRET}
spring.jwt.expirationMs=180000
spring.config.import=optional:file:.env[.properties]
